services:
    mistserver:
        image: ddvtech/mistserver_alpine_minimal
        container_name: mistserver
        volumes:
          - ./config/config.json:/config.json
          - ./vod:/video
        shm_size: '10gb'
        network_mode: 'host'
        restart: always
